### ISSUE TITLE
Kamban Board Recipes App

### ISSUE THREAD

**Issue by luccamicale** [AlaaShaheen2/Recipe-app#14]
Hi Reviewer!! 💯 👍 
we are @AlaaShaheen2 and @luccamicale 

-Team Member 1: @AlaaShaheen2 
-Team Member 2: @luccamicale 
👍 🔢 💯 🥇 

Kamban Board : https://github.com/AlaaShaheen2/Recipe-app/projects/1

**Comment by mckent05** [comment]
Hi @luccamicale, 

# STATUS: INVALID REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that does not have a link to the Kanban board you have setup with your partner, please fix this 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
- There are about 3 card on your Kanban without descriptions. Kindly add descriptions to all cards.

![image](https://user-images.githubusercontent.com/27709832/218570625-72ef969c-ae50-4140-838a-a52d5967be8c.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luccamicale** [comment]
Now I completed the description in the tasks

**Comment by omar-muhamad** [comment]
# Approved ✔
### Hi Team,

Great job, Your project is complete!  
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
